import React from 'react';
import { Page } from '../types';

interface TermsViewProps {
  onNavigate: (page: Page) => void;
}

export const TermsView: React.FC<TermsViewProps> = ({ onNavigate }) => {
  return (
    <div className="flex flex-col gap-12 pb-20">
      {/* Header Section */}
      <section className="text-center pt-4 max-w-3xl mx-auto space-y-4">
        <h1 className="font-headline text-3xl md:text-5xl font-bold text-trust-navy">Terms of Service</h1>
        <p className="font-body text-base md:text-lg text-on-surface-variant max-w-2xl mx-auto">
          Please read these terms carefully before using our platform or scheduling advisory services.
        </p>
        <p className="font-label text-xs font-semibold text-outline">Last Updated: October 26, 2026</p>
      </section>

      {/* Terms Content */}
      <div className="glass-card rounded-3xl shadow-sm p-6 md:p-12 max-w-3xl mx-auto space-y-10 border border-outline-variant/30">
        <section className="space-y-3">
          <h2 className="font-headline text-xl md:text-2xl font-bold text-trust-navy flex items-center gap-3">
            <span className="material-symbols-outlined text-primary">handshake</span>
            Agreement to Terms
          </h2>
          <p className="font-body text-sm md:text-base text-on-surface-variant leading-relaxed">
            By accessing or using the Insurance Made Simple platform, calculators, or consultation booking services, you agree to be bound by these Terms of Service. These terms apply to all visitors, users, and clients.
          </p>
        </section>

        <section className="space-y-3 pt-4 border-t border-outline-variant/20">
          <h2 className="font-headline text-xl md:text-2xl font-bold text-trust-navy flex items-center gap-3">
            <span className="material-symbols-outlined text-secondary">devices</span>
            Use of Calculators &amp; Estimates
          </h2>
          <p className="font-body text-sm md:text-base text-on-surface-variant leading-relaxed">
            Calculations generated by our Life Insurance Need and Retirement Income tools are estimates provided for educational purposes only. Final policy rates, death benefits, and annuity payout schedules are subject to formal carrier underwriting and policy contract terms.
          </p>
        </section>

        <section className="space-y-3 pt-4 border-t border-outline-variant/20">
          <h2 className="font-headline text-xl md:text-2xl font-bold text-trust-navy flex items-center gap-3">
            <span className="material-symbols-outlined text-tertiary">copyright</span>
            Intellectual Property
          </h2>
          <p className="font-body text-sm md:text-base text-on-surface-variant leading-relaxed">
            All original content, visual designs, logos, WebGL visualizations, and educational guides remain the exclusive property of Insurance Made Simple and its licensors.
          </p>
        </section>

        <section className="space-y-3 pt-4 border-t border-outline-variant/20">
          <h2 className="font-headline text-xl md:text-2xl font-bold text-trust-navy flex items-center gap-3">
            <span className="material-symbols-outlined text-primary">mail</span>
            Contact Legal
          </h2>
          <p className="font-body text-sm md:text-base text-on-surface-variant leading-relaxed">
            If you have questions regarding these terms, please contact us at: <br />
            <strong className="text-trust-navy font-semibold">legal@insurancemadesimple.com</strong>
          </p>
        </section>
      </div>

      <div className="text-center">
        <button
          onClick={() => onNavigate('home')}
          className="px-6 py-2.5 bg-primary text-on-primary font-label font-semibold text-sm rounded-full shadow-sm hover:opacity-90"
        >
          Return Home
        </button>
      </div>
    </div>
  );
};
